include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "lib/generated/**"

  errors:
    # 메모리 누수 및 잠재적 버그 방지
    close_sinks: error
    cancel_subscriptions: error
    unawaited_futures: error
    use_build_context_synchronously: error

linter:
  rules:
    # 1. 가독성 및 일관성
    avoid_print: true
    sort_child_properties_last: true
    prefer_single_quotes: true
    require_trailing_commas: true
    use_full_hex_values_for_flutter_colors: true
    
    # 2. 성능 최적화
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    unnecessary_const: true
    unnecessary_new: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # 3. 코드 효율성 및 안정성
    prefer_final_fields: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    use_key_in_widget_constructors: true