name: flutter_kimchi_run
description: "A mobile game built with Flutter and Unity WebGL, using game content from a YouTube tutorial by Nicolas from Nomad Coders."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod:
  riverpod_annotation:

  # Routing
  go_router:

  # Data & Serialization
  json_annotation:
  freezed_annotation:

  # Firebase
  firebase_core:
  firebase_auth:
  firebase_storage:
  cloud_firestore:
  firebase_crashlytics:
  firebase_analytics:

  ## Debounce & Throttle
  easy_debounce:

  ## Security
  crypto:

  ## Image
  flutter_svg:
  image_picker:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner:
  retrofit_generator:
  riverpod_generator:
  json_serializable:
  freezed:
  flutter_gen_runner:
  custom_lint_builder:
  analyzer:
  analyzer_plugin:

  # Linting
  flutter_lints:
  riverpod_lint:
  custom_lint:

flutter:
  uses-material-design: true
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
  assets:
    - assets/fonts/

flutter_gen:
  output: lib/gen/
  integrations:
    image: true
    flutter_svg: true
  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

